#!/bin/sh
'''exec' "/Users/nguyenho/Documents/Zalo Received Files/AI_upload_Question/venv/bin/python3" "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from opentelemetry.instrumentation.auto_instrumentation import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
